version: '2'
services:
  static-server:
    image: static-server
    container_name: static-server
    ports:
      - 8001:8001
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  dynamic-server:
    image: dynamic-server
    container_name: dynamic-server
    ports:
      - 8002:8002
    networks:
      static-network:
        ipv4_address: 172.20.128.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
